/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component.sms;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Codepal
 */
public class SMSRechargePanel extends javax.swing.JPanel {
  private JLabel balanceLabel;
    private JTextField rechargeAmountField;
    private JButton purchaseButton;
    /**
     * Creates new form SMSRechargePanel
     */
    public SMSRechargePanel() {
        initComponents();
        init();
        setLayout(new GridLayout(3, 2));
        add(new JLabel("Current Balance:"));
        add(balanceLabel);
        add(new JLabel("Recharge Amount (KES):"));
        add(rechargeAmountField);
        add(new JLabel());
        add(purchaseButton);

        purchaseButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int amount = Integer.parseInt(rechargeAmountField.getText());
                    if (amount < 100) {
                        JOptionPane.showMessageDialog(SMSRechargePanel.this, "Minimum recharge amount is 100 KES.");
                        return;
                    }

                    boolean success = makeAPICall(amount);
                    if (success) {
                        int currentBalance = Integer.parseInt(balanceLabel.getText());
                        int newBalance = currentBalance + amount;
                        balanceLabel.setText(String.valueOf(newBalance));
                        JOptionPane.showMessageDialog(SMSRechargePanel.this, "Recharge successful. New balance: " + newBalance + " KES");
                    } else {
                        JOptionPane.showMessageDialog(SMSRechargePanel.this, "Failed to recharge. Please try again later.");
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(SMSRechargePanel.this, "Please enter a valid amount.");
                }
            }
        });
    }
  

    // Mock method to simulate API call
    private boolean makeAPICall(int amount) {
        // Here you would typically make an actual API call
        // For demonstration, let's assume the call is successful if the amount is greater than 0
        return amount > 0;
    }

 

    private void init() {
        balanceLabel = new JLabel("0");
        rechargeAmountField = new JTextField();
        purchaseButton = new JButton("Purchase Credit");
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("SMS Credit Recharge");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(300, 150);
        frame.getContentPane().add(new SMSRechargePanel());
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
