/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Codepal
 */
public class LeadPanel extends javax.swing.JPanel {
private JTextField nameField;
    private JTextField emailField;
    private JButton addButton;
    private JList<String> leadList;
    private DefaultListModel<String> listModel;

    private List<String> leads;
    /**
     * Creates new form LeadPanel
     */
    public LeadPanel() {
        initComponents();
        setLayout(new BorderLayout());

        // Create input fields
        JPanel inputPanel = new JPanel(new GridLayout(2, 2));
        inputPanel.add(new JLabel("Name:"));
        nameField = new JTextField();
        inputPanel.add(nameField);
        inputPanel.add(new JLabel("Email:"));
        emailField = new JTextField();
        inputPanel.add(emailField);

        // Create add button
        addButton = new JButton("Add Lead");
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                addLead();
            }
        });

        // Create lead list
        listModel = new DefaultListModel<>();
        leadList = new JList<>(listModel);
        JScrollPane listScrollPane = new JScrollPane(leadList);

        // Create button panel
        JPanel buttonPanel = new JPanel(new GridLayout(1, 2));
        JButton editButton = new JButton("Edit");
        JButton deleteButton = new JButton("Delete");
        editButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                editLead();
            }
        });
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteLead();
            }
        });
        buttonPanel.add(editButton);
        buttonPanel.add(deleteButton);

        // Add components to panel
        add(inputPanel, BorderLayout.NORTH);
        add(addButton, BorderLayout.CENTER);
        add(listScrollPane, BorderLayout.CENTER);
        add(buttonPanel, BorderLayout.SOUTH);

        // Initialize leads list
        leads = new ArrayList<>();
    }
     private void addLead() {
        String name = nameField.getText();
        String email = emailField.getText();
        String leadInfo = name + " - " + email;
        leads.add(leadInfo);
        listModel.addElement(leadInfo);
        clearFields();
    }

    private void editLead() {
        int selectedIndex = leadList.getSelectedIndex();
        if (selectedIndex != -1) {
            String editedName = JOptionPane.showInputDialog(this, "Enter updated name:");
            String editedEmail = JOptionPane.showInputDialog(this, "Enter updated email:");
            if (editedName != null && editedEmail != null) {
                String editedLeadInfo = editedName + " - " + editedEmail;
                leads.set(selectedIndex, editedLeadInfo);
                listModel.set(selectedIndex, editedLeadInfo);
            }
        }
    }

    private void deleteLead() {
        int selectedIndex = leadList.getSelectedIndex();
        if (selectedIndex != -1) {
            leads.remove(selectedIndex);
            listModel.remove(selectedIndex);
        }
    }

    private void clearFields() {
        nameField.setText("");
        emailField.setText("");
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame("Lead Management");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.getContentPane().add(new LeadPanel());
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
