/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventory;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Codepal
 */
public class PurchasePanel extends javax.swing.JPanel {
    private JTextField supplierCodeField;
    private JComboBox<String> productComboBox;
    private JTextField quantityField;
    private JTextField unitField;
    private JButton addButton;
    private JTable purchaseTable;
    private DefaultTableModel tableModel;
    /**
     * Creates new form PurchasePanel
     */
    public PurchasePanel() {
        initComponents();
        setLayout(new BorderLayout());

        // Panel for supplier code input
        JPanel supplierPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel supplierCodeLabel = new JLabel("Supplier Code:");
        supplierCodeField = new JTextField(10);
        supplierPanel.add(supplierCodeLabel);
        supplierPanel.add(supplierCodeField);

        // Panel for product selection and quantity input
        JPanel productPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        JLabel productLabel = new JLabel("Product:");
        productComboBox = new JComboBox<>();
        productComboBox.addItem("Product 1");
        productComboBox.addItem("Product 2");
        quantityField = new JTextField(5);
        JLabel quantityLabel = new JLabel("Quantity:");
        unitField = new JTextField(5);
        JLabel unitLabel = new JLabel("Unit:");
        addButton = new JButton("Add");
        productPanel.add(productLabel);
        productPanel.add(productComboBox);
        productPanel.add(quantityLabel);
        productPanel.add(quantityField);
        productPanel.add(unitLabel);
        productPanel.add(unitField);
        productPanel.add(addButton);

        // Table to display selected products
        tableModel = new DefaultTableModel(new Object[]{"Product", "Quantity", "Unit"}, 0);
        purchaseTable = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(purchaseTable);

        // Button to save and print invoice
        JButton savePrintButton = new JButton("Save & Print");

        // Add components to the main panel
        add(supplierPanel, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(productPanel, BorderLayout.SOUTH);
        add(savePrintButton, BorderLayout.EAST);

        // ActionListener for add button
        addButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String product = (String) productComboBox.getSelectedItem();
                String quantity = quantityField.getText();
                String unit = unitField.getText();
                tableModel.addRow(new Object[]{product, quantity, unit});
            }
        });
    }
  public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Purchase Panel");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(new PurchasePanel());
            frame.pack();
            frame.setVisible(true);
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
