/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package inventory;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import models.Supplier;
import models.SupplierGroup;
import net.miginfocom.swing.MigLayout;
/**
 *
 * @author Codepal
 */
public class SupplierManagementPanel extends javax.swing.JPanel {
    private List<SupplierGroup> supplierGroups;
    /**
     * Creates new form SupplierManagementPanel
     */
    public SupplierManagementPanel() {
        initComponents();
        setLayout(new MigLayout("", "[grow]", "[][]"));
        supplierGroups = new ArrayList<>();
        SupplierGroup dummyGroup = new SupplierGroup("Dummy Group");
        dummyGroup.addSupplier(new Supplier("Supplier 1", "Contact 1", dummyGroup));
        dummyGroup.addSupplier(new Supplier("Supplier 2", "Contact 2", dummyGroup));
        supplierGroups.add(dummyGroup);

        // Create collapsible panels for each supplier group
        for (SupplierGroup group : supplierGroups) {
            add(createCollapsiblePanel(group));
        }
    }

    // Method to create a collapsible panel for a supplier group
    private JPanel createCollapsiblePanel(SupplierGroup group) {
        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createTitledBorder(null, group.getGroupName(), TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font("Arial", Font.BOLD, 14), Color.BLACK));

        JTable supplierTable = createSupplierTable(group.getSuppliers());
        JScrollPane scrollPane = new JScrollPane(supplierTable);
        panel.add(scrollPane, BorderLayout.CENTER);

        // Collapse/Expand functionality
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isRightMouseButton(e)) {
                    // Show context menu to add supplier or edit supplier group
                    JPopupMenu popupMenu = new JPopupMenu();
                    JMenuItem addSupplierItem = new JMenuItem("Add Supplier");
                    JMenuItem editGroupItem = new JMenuItem("Edit Group");
                    popupMenu.add(addSupplierItem);
                    popupMenu.add(editGroupItem);
                    popupMenu.show(panel, e.getX(), e.getY());
                }
            }
        });

        return panel;
    }

    // Method to create a JTable for suppliers
    private JTable createSupplierTable(List<Supplier> suppliers) {
        String[] columnNames = {"Supplier Name", "Contact"};
        Object[][] data = new Object[suppliers.size()][2];

        for (int i = 0; i < suppliers.size(); i++) {
            Supplier supplier = suppliers.get(i);
            data[i][0] = supplier.getName();
            data[i][1] = supplier.getContact();
        }

        return new JTable(data, columnNames);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Supplier Management");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.add(new SupplierManagementPanel());
            frame.pack();
            frame.setVisible(true);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
